import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAlert } from '../contexts/AlertContext'
const Home: NextPage = () => {
const {danger,warning,success} = useAlert();



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <button onClick={()=>{danger("Alert 1")}}>Show Alert1</button>
      <div>xx</div>
      <button onClick={()=>{warning("Alert 2")}}>Show Alert2</button>

      <button onClick={()=>{success("Alert 3")}}>Show Alert2</button>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
